---
driver:
  name: vagrant

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://docs.vagrantup.com/v2/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :audit_only

## require_chef_omnibus specifies a specific chef version to install. You can
## also set this to `true` to always use the latest version.
## see also: https://docs.chef.io/config_yml_kitchen.html

#  require_chef_omnibus: 12.5.0

platforms:
  - name: win2012r2
    driver:
      box: win2012r2
      box_url:  https://s3-us-west-1.amazonaws.com/scottford.io/win2012r2-datacenter-nocm-1.0.2.box
      customize:
        memory: 2048
        cpus: 2
  

suites:
  - name: default
    attributes:
